#!/usr/bin/env python3.9



print("hello")
from person import Person

def main():
	#f = Person(5)
	#print(f.get())
	#f.set(7)
	#print(f.get())
	#this = f.get()
	#fib_result = f.fib_py()
	#print("fib", this, "is equal to:", fib_result)
	f = Person(0)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(1)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(2)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(3)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(4)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(5)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(6)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(7)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(8)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(9)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(10)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
	f = Person(18)
	fib_result = f.fib_py()
	print("fib", f.get(), "is equal to:", fib_result)
if __name__ == '__main__':
	main()
